### PR TITLE
Extend ESLint config with TypeScript support

### PR DESCRIPTION
**Pull request by zweimach**
What this PR does is:
- [x] [Extend default ESLint config](https://create-react-app.dev/docs/setting-up-your-editor/#experimental-extending-the-eslint-config) with TypeScript and Prettier plugins
- [x] Create ESLint config in project folder so that IDEs can use ESLint properly
- [x] Remove `parser` option in `.prettierrc.json` so that Prettier can infer what to use
- [x] Add `husky` and `lint-staged` to enforce style formatting and linting with git pre-commit hook

Please review my changes, Mas @fushar.

### CODE REVIEW

**Review by fushar — APPROVED** [review]
Looks good. Thanks for your contribution!

**Comment by zweimach** [comment]
Mas @fushar, I forgot to mention that this PR adds type-aware lint rules and triggers tons of errors.
You should adjust, pick, and ignore rules that can hinder further development.

**Comment by fushar** [comment]
Sorry, I'm reverting master back. This PR breaks the build (`yarn build`), and I don't really have time to investigate this issue right now.

**Comment by fushar** [comment]
Feel free to re-raise this PR after making sure that `yarn build` succeeds, ya.

**Pull request merged**
